services:
  front: 
    build: ./php
    image: mhaili/cp-php:latest
    restart : unless-stopped
    ports:
      - "8090:80"
    #volumes:
    # - .php/www:/var/www/html
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=rootpwd
      - DB_NAME=cp
      - DB_PORT=3306

    depends_on:
      - db
  db:
    build: ./mysql
    image: mhaili/cp-mysql:latest
    #ports:
    #  -"3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
    volumes:
      - mysql-cp-data:/var/lib/mysql

volumes:
  mysql-cp-data: